import type { Metadata } from 'next'
import './globals.css'
import Head from 'next/head'

// Font : "Monocraft","Mabry Pro","Gotham Bold","Spline Sans","Helvetica Neue","Google Sans","Work Sans",Arial,sans-serif

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossOrigin="anonymous"></link>
        <link href="https://fonts.googleapis.com/css?family=Spline+Sans|Work+Sans|Fira+Mono|Fira+Sans|Google+Sans|Lexend+Deca&amp;display=swap" rel="stylesheet"></link>
      </Head>
      <body className={"None"}>
        {children}
      </body>
    </html>
  )
}
